on: push
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Install modules
        working-directory: 
        run: npm install
  pa11y:
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v1
      - uses: browser-actions/setup-chrome@latest
      - uses: booleans-oss/pa11y-actions.git@latest
        with:
          start: start
          port: '3000'
          
